const numero = "#24";
let nome = "name";
let cognome = "surname";
let colore = "color";
let textname = prompt("name");
let textsurname = prompt("surname");
let textcolor = prompt("color");
const password ="name"+"surname"+"color"+"#24";
document.getElementById("password").innerHTML = `la tua password è: ${password}`;
